# Generated by Django 5.2.17 on 2026-08-31 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('MED', 'Medical'), ('FIRE_RESCUE', 'Fire Rescue'), ('POLICE_SECURITY', 'Police/Security'), ('NGO', 'Non-Governmental Organization')], max_length=20)),
                ('address', models.TextField()),
                ('verification_document', models.FileField(upload_to='verification_documents/')),
                ('verification_status', models.CharField(choices=[('PEND', 'Pending'), ('VERIF', 'Verified'), ('REJ', 'Rejected')], default='PEND', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
