# Generated by Django 5.2.17 on 2026-09-06 09:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('MEDICAL', 'Medical'), ('FIRE', 'Fire'), ('CRIME_SECURITY', 'Crime/Security'), ('MISSING_PERSON', 'Missing Person'), ('BLOOD_BANK', 'Blood Bank')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_address', models.CharField(blank=True, max_length=255)),
                ('people_affected', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('SERIOUS', 'Serious'), ('MINOR', 'Minor'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('road_blocked', models.BooleanField(blank=True, null=True)),
                ('fire_smoke', models.BooleanField(blank=True, null=True)),
                ('severe_bleeding', models.BooleanField(blank=True, null=True)),
                ('person_trapped', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('DISPATCHING', 'Dispatching'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
