# Generated by Django 5.2.17 on 2026-09-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('MATCHING', 'Matching'), ('ALERTING', 'Alerting Responders'), ('ACCEPTED', 'Accepted'), ('ENROUTE', 'Enroute'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
