# Generated by Django 5.2.17 on 2026-09-06 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOTIFIED', 'Notified'), ('ACCEPTED', 'Accepted')], default='NOTIFIED', max_length=10)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_organizations', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_organizations', to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('incident', 'organization'), name='unique_incident_organization')],
            },
        ),
    ]
