# Generated by Django 5.2.17 on 2026-09-07 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentvolunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incidentvolunteer',
            constraint=models.UniqueConstraint(fields=('incident', 'volunteer'), name='unique_incident_volunteer'),
        ),
    ]
